name: Build and Release Extension

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.0.0

      - name: Install dependencies
        run: pnpm install

      - name: Build extension
        run: pnpm build

      - name: Create distribution package
        run: |
          mkdir -p temp/intender-chrome/chrome-mv3
          cp -r .output/chrome-mv3/* temp/intender-chrome/chrome-mv3/
          cd temp
          zip -r ../.output/intender-chrome.zip intender-chrome/
          cd ..
          rm -rf temp

      - name: Get version from package.json
        id: version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          files: .output/intender-chrome.zip
          generate_release_notes: true
          draft: false
          prerelease: false
          name: Release v${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
